### ISSUE TITLE
Duplicate taxon label error

### ISSUE THREAD

**Issue by ERRMoody** [ytabatabaee/CASTLES#1]
If I am correct, then theoretically this should work with duplicate taxa in gene trees, however I get this error when trying to use a species-tree inferred under ASTRAL, with a collection of gene-trees:

`dendropy.dataio.newickreader.NewickReader.NewickReaderDuplicateTaxonError: Error parsing data source 'castle_gt_input.trees' on line 1 at column 1481: Multiple occurrences of the same taxa on trees are not supported: trees with duplicate node labels can only be processed if the labels are not parsed as operational taxonomic unit concepts but instead as simply node labels by specifying 'suppress_internal_node_taxa=True, suppress_leaf_node_taxa=True'.`

When trying to add these flags though I also get errors:
`castles.py: error: unrecognized arguments: suppress_internal_node_taxa=True, suppress_leaf_node_taxa=True`

`castles.py: error: unrecognized arguments: suppress_internal_node_taxa=True suppress_leaf_node_taxa=True`

**Comment by smirarab** [comment]
Do you mean multiple-copy or multiple individuals (alleles)? If multiple alleles, the code should work and we can try to debug it. If you mean multiple copies, the theory is not developed for the DLCoal model. It only covers the MSC model for now. So, even if we can make the code work under multiple copies, it is not clear that it would have correct statistical properties.

**Comment by smirarab** [comment]
By the way, if you did mean multiple copies (what I suspect given that you work on LUCA), we'd be happy to discuss a different path. We can use another method called DISCO to create single copy gene trees and use those as input to CASTLES.
