### ISSUE TITLE
IndexError when running CASTLES

### ISSUE THREAD

**Issue by Avehi** [ytabatabaee/CASTLES#2]
Hello! 
I am trying to use CASTLES to estimate branch lengths of a species tree topology I generated with ASTRAL. I was able to annotate the species tree topology with a local installation of ASTER. However, when I run castles.py, I get this error:

Number of species: 55
Number of genes: 5969

Calculating lengths in post-order traversal of internal nodes:
Traceback (most recent call last):
  File "/home/avehi/Biotools/CASTLES-1.3.0/castles.py", line 306, in <module>
    castles(st, gts, tns)
  File "/home/avehi/Biotools/CASTLES-1.3.0/castles.py", line 210, in castles
    label_dict = process_node_annotation(node.label)
  File "/home/avehi/Biotools/CASTLES-1.3.0/castles.py", line 21, in process_node_annotation
    label_dict['support'] = float(annotations[1])
IndexError: list index out of range

The input files are rather large but I could email them to you, if you'd like. 

Thanks very much in advance!!

**Comment by ytabatabaee** [comment]
Hi,

Thanks for using CASTLES. Could you please email me the input files (including the ASTER annotated tree) at syt3@illinois.edu?

Best,
Yasamin
